# Contains a list of all items the player can be given
# at any point during the map.
# Last Edited: 6/24/17
# Author: Sybillian


give @s minecraft:wooden_sword 1 1 {Unbreakable:1b,HideFlags:38,display:{LocName:"Wooden Scythe",Lore:[" ","§7When in main hand:","§7 0.6 Attack Speed","§7 5 Attack Damage"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:5,Operation:0,UUIDLeast:747281,UUIDMost:291082,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-3.2,Operation:0,UUIDLeast:477759,UUIDMost:790980,Slot:"mainhand"}]}
give @s minecraft:stone_sword 1 1 {Unbreakable:1b,HideFlags:38,display:{LocName:"Stone Scythe",Lore:[" ","§7When in main hand:","§7 0.6 Attack Speed","§7 6 Attack Damage"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:6,Operation:0,UUIDLeast:747281,UUIDMost:291082,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-3.2,Operation:0,UUIDLeast:477759,UUIDMost:790980,Slot:"mainhand"}]}
give @s minecraft:golden_sword 1 1 {Unbreakable:1b,HideFlags:38,display:{LocName:"Golden Scythe",Lore:[" ","§7When in main hand:","§7 0.6 Attack Speed","§7 5 Attack Damage"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:5,Operation:0,UUIDLeast:747281,UUIDMost:291082,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-3.2,Operation:0,UUIDLeast:477759,UUIDMost:790980,Slot:"mainhand"}]}
give @s minecraft:iron_sword 1 1 {Unbreakable:1b,HideFlags:38,display:{LocName:"Iron Scythe",Lore:[" ","§7When in main hand:","§7 0.6 Attack Speed","§7 7 Attack Damage"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:7,Operation:0,UUIDLeast:747281,UUIDMost:291082,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-3.2,Operation:0,UUIDLeast:477759,UUIDMost:790980,Slot:"mainhand"}]}
give @s minecraft:diamond_sword 1 1 {Unbreakable:1b,HideFlags:38,display:{LocName:"Diamond Scythe",Lore:[" ","§7When in main hand:","§7 0.6 Attack Speed","§7 9 Attack Damage"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:9,Operation:0,UUIDLeast:747281,UUIDMost:291082,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-3.2,Operation:0,UUIDLeast:477759,UUIDMost:790980,Slot:"mainhand"}]}

give @s minecraft:shears 1 1 {Unbreakable:1b,HideFlags:38,display:{LocName:"Wooden Dagger",Lore:[" ","§7When in main hand:","§7 Old Combat","§7 2 Attack Damage"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:2,Operation:0,UUIDLeast:747281,UUIDMost:291082,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:20,Operation:0,UUIDLeast:477759,UUIDMost:790980,Slot:"mainhand"}]}
give @s minecraft:shears 1 2 {Unbreakable:1b,HideFlags:38,display:{LocName:"Stone Dagger",Lore:[" ","§7When in main hand:","§7 Old Combat","§7 3 Attack Damage"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:3,Operation:0,UUIDLeast:747281,UUIDMost:291082,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:20,Operation:0,UUIDLeast:477759,UUIDMost:790980,Slot:"mainhand"}]}
give @s minecraft:shears 1 3 {Unbreakable:1b,HideFlags:38,display:{LocName:"Golden Dagger",Lore:[" ","§7When in main hand:","§7 Old Combat","§7 2 Attack Damage"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:2,Operation:0,UUIDLeast:747281,UUIDMost:291082,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:20,Operation:0,UUIDLeast:477759,UUIDMost:790980,Slot:"mainhand"}]}
give @s minecraft:shears 1 4 {Unbreakable:1b,HideFlags:38,display:{LocName:"Iron Dagger",Lore:[" ","§7When in main hand:","§7 Old Combat","§7 4 Attack Damage"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:4,Operation:0,UUIDLeast:747281,UUIDMost:291082,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:20,Operation:0,UUIDLeast:477759,UUIDMost:790980,Slot:"mainhand"}]}
give @s minecraft:shears 1 5 {Unbreakable:1b,HideFlags:38,display:{LocName:"Diamond Dagger",Lore:[" ","§7When in main hand:","§7 Old Combat","§7 5 Attack Damage"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:5,Operation:0,UUIDLeast:747281,UUIDMost:291082,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:20,Operation:0,UUIDLeast:477759,UUIDMost:790980,Slot:"mainhand"}]}
give @s minecraft:shears 1 6 {Unbreakable:1b,HideFlags:38,display:{LocName:"§cTotem of Ignition",Lore:["§4When you're hit while holding this totem,","§4nearby enemies will be set ablaze!"]}}
give @s minecraft:shears 1 7 {Unbreakable:1b,HideFlags:38,display:{LocName:"§3Totem of Frostbite",Lore:["§9When you're hit while holding this totem,","§9nearby enemies will be frozen solid!"]}}
give @s minecraft:shears 1 8 {Unbreakable:1b,HideFlags:38,display:{LocName:"§7Totem of Decay",Lore:["§8When you're hit while holding this totem,","§8nearby enemies will begin to wither away!"]}}
give @s minecraft:totem_of_undying 1 0 {display:{LocName:"§eTotem of Undying",Lore:["§6When you're killed while holding this totem,","§6the gods will give you a second chance."]}}

give @s minecraft:bow 1 1 {Unbreakable:1b,HideFlags:5,ench:[{id:48,lvl:10}],display:{LocName:"§dAstral Bow",Lore:["§5Arrows launched from this weapon will","§5be freed from gravity's clutches."]}}

give @s minecraft:shield 1 0 {Unbreakable:1b,HideFlags:36,display:{LocName:"§7Iron Shield"},BlockEntityTag:{Patterns:[{Pattern:"gra",Color:7},{Pattern:"gru",Color:7}],Base:15},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:-0.1,Operation:1,UUIDLeast:400931,UUIDMost:198129,Slot:"offhand"},{AttributeName:"generic.armor",Name:"generic.armor",Amount:2,Operation:0,UUIDLeast:599334,UUIDMost:329696,Slot:"offhand"}]}
give @s minecraft:shield 1 0 {Unbreakable:1b,HideFlags:36,display:{LocName:"§9Diamond Shield"},BlockEntityTag:{Patterns:[{Pattern:"gra",Color:12},{Pattern:"gru",Color:12}],Base:15},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:-0.2,Operation:1,UUIDLeast:400931,UUIDMost:198129,Slot:"offhand"},{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUIDLeast:599334,UUIDMost:329696,Slot:"offhand"}]}


#{Inventory:[{Slot:100b,id:"minecraft:itemID"}]}